language: "en"

pipeline:
- name: "MitieNLP"
  # language model to load
  model: "data/total_word_feature_extractor.dat"
  cache_dir: null
- name: MitieTokenizer
- name: MitieFeaturizer
- name: RegexFeaturizer
- name: "SklearnIntentClassifier"
  num_threads: 8
  n_jobs: 8
  C: [59, 69, 90, 100]
  # Specifies the kernel to use with C-SVM.
  kernels: ["linear"]
  # Gamma parameter of the C-SVM.
  "gamma": [0.1]
  # We try to find a good number of cross folds to use during
  "max_cross_validation_folds": 5
  # Scoring function used for evaluating the hyper parameters.
  "scoring_function": "f1_weighted"


