language: "en"

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 100
    batch_strategy: "balanced"
    use_masked_language_model: true
    tensorboard_log_level: "epoch"
    tensorboard_log_directory: "log"
    drop_rate: 0.1
    negative_margin_scale: 0.8
    maximum_positive_similarity: 0.6
    maximum_negative_similarity: -0.2
    similarity_type: "inner"
    embedding_dimension: 100
    share_hidden_layers: false
    transformer_size: 128
    number_of_transformer_layers: 4
    entity_recognition: false
    number_of_attention_heads: 128
    weight_sparsity: 0.8
    hidden_layers_sizes: 
      text: [256, 256, 128, 64]
      label: [256, 256, 128, 64]
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
