language: "en"

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    features: [
      ["low", "title"], 
      ["bias", "suffix3"], 
      ["upper", "pattern"]
      #["dep", "ents", "cats"]
    ]
    BILOU_flag: true
    # This is the value given to sklearn_crfcuite.CRF tagger before training.
    max_iterations: 300
    L1_c: 0.0001
    L2_c: 0.2
  - name: DIETClassifier
    epochs: 300
    batch_strategy: "balanced"
    learning_rate: 0.0001
    use_masked_language_model: true
    tensorboard_log_level: "epoch"
    tensorboard_log_directory: "log"
    drop_rate: 0.01
    batch_size: [64, 128]
    negative_margin_scale: 0.6
    maximum_positive_similarity: 0.6
    maximum_negative_similarity: -0.2
    similarity_type: "inner"
    embedding_dimension: 50
    number_of_negative_examples: 20
    share_hidden_layers: false
    transformer_size: 128
    number_of_transformer_layers: 3
    number_of_attention_heads: 128
    weight_sparsity: 0.8
    entity_recognition: true
    intent_classification: true
    evaluate_every_number_of_epochs: 40
    evaluate_on_number_of_examples: 500
    random_seed: 10
    hidden_layers_sizes: 
      text: [256]
      label: [256]