language: "en"

pipeline:
- name: "MitieNLP"
  # language model to load
  model: "data/total_word_feature_extractor.dat"
  cache_dir: null
- name: MitieTokenizer
- name: MitieFeaturizer
- name: RegexFeaturizer
#- name: "CRFEntityExtractor"
#  features: [
#    ["low", "title"], 
#    ["bias", "suffix3"], 
#    ["upper", "pos2"]
#    #["dep", "ents", "cats"]
#  ]
#  BILOU_flag: true
  # This is the value given to sklearn_crfcuite.CRF tagger before training.
#  max_iterations: 300
#  L1_c: 0.0001
#  L2_c: 0.02
- name: "SklearnIntentClassifier"
  num_threads: 8
  n_jobs: 8
  # This is used with the ``kernel`` hyperparameter in GridSearchCV.
  C: [1, 2, 5, 10, 30, 100]
  # Specifies the kernel to use with C-SVM.
  kernels: ["linear"]
  # Gamma parameter of the C-SVM.
  "gamma": [0.1]
  # We try to find a good number of cross folds to use during
  "max_cross_validation_folds": 5
  # Scoring function used for evaluating the hyper parameters.
  "scoring_function": "f1_weighted"


